---
title: "Applying Support Vector Machine (SVM) Algorithm to identify S&P500 trend"
output: html_notebook
---


```{r}
#install.packages("quantmod")
#install.packages("e1071")

library(quantmod)
library(e1071)

# Importing the dataset
startDate = as.Date("2011-01-01")
endDate = as.Date("2018-06-30") 
getSymbols("^GSPC",src="yahoo",from=startDate,to=endDate) 
dataset=data.frame(GSPC)
dim(dataset)
str(dataset)

#RSI indicator
relativeStrengthIndex20=RSI(Op(GSPC),n=20)
summary(relativeStrengthIndex20)
plot(relativeStrengthIndex20)

# Exponential Moving Average Indicator
exponentialMovingAverage20=EMA(Op(GSPC),n=20)
head(exponentialMovingAverage20)
summary(exponentialMovingAverage20)
plot(exponentialMovingAverage20)

# Difference in Exponential Moving Average
exponentialMovingAverageDiff <- Op(GSPC) - exponentialMovingAverage20
head(exponentialMovingAverageDiff)
summary(exponentialMovingAverageDiff)
plot(exponentialMovingAverageDiff)

# MACD Indicator
MACD <- MACD(Op(GSPC),fast = 12, slow = 26, signal = 9, type = "EMA", histogram = TRUE)
plot(MACD)
tail(MACD)
summary(MACD)
MACDsignal <- MACD[,2]
plot(MACDsignal)

# Bollinger Band indicator
BollingerBands <- BBands(Op(GSPC),n=20,sd=2)
tail(BollingerBands)
summary(BollingerBands)
plot(BollingerBands)

# % Change BB
PercentageChngpctB <- BollingerBands[,4]
tail(PercentageChngpctB)
summary(PercentageChngpctB)
plot(PercentageChngpctB)





```

```{r}
# Price (Closes above Open = 1, Closes below Open = 0)
Price=ifelse(dataset[4]>dataset[1], 1,0)
tail(Price)
tail(dataset)
plot(Price)

dataset1<-data.frame(relativeStrengthIndex20, exponentialMovingAverage20, MACDsignal, PercentageChngpctB, Price)

# Size of Data
str(dataset1)
dim(dataset1)

#Checking for missing data
d3=dataset1
for(i in 1:ncol(d3))
   {
    print(colnames(d3[i]))
    print(sum(is.na(d3[i])))
   }

dataset1 = na.omit(dataset1)

#Checking for missing data again
dim(dataset1)
d3=dataset1
for(i in 1:ncol(d3))
   {
    print(colnames(d3[i]))
    print(sum(is.na(d3[i])))
   }

colnames(dataset1)=c ("RSI20", "EMA20", "MACDsignal", "BB", "Price")

# Exploring the data set components
str(dataset1)

# Encoding the target feature as factor
dataset1$Price=factor(dataset1$Price, levels = c(0, 1))



```

```{r}

# Splitting the dataset into the Training set and Test set
library(caTools)
set.seed(123)
split = sample.split(dataset1$Price, SplitRatio = 0.8)
training_set = subset(dataset1, split == TRUE)
test_set = subset(dataset1, split == FALSE)

# Feature Scaling (Normalization and dropping the predicted variable)
training_set[-5] = scale(training_set[-5])
test_set[-5] = scale(test_set[-5])

# Applying Kernel SVM Model on the Training set

library(e1071)
classifier = svm(formula = Price ~ .,
                 data = training_set,
                 type = 'C-classification',
                 kernel = 'radial')

# Predicting the Test set results
predict_val = predict(classifier, newdata = test_set[-5])

# Confusion Matrix
cm = table(test_set[, 5], predict_val)
print(cm)
# Evaluating Model Accuracy on test data set using Confusion Matrix
Model_Accuracy=(cm[1,1] + cm[2,2])/ (cm[1,1] + cm[1,2] + cm[2,1] + cm[2,2])
print("Model Accuracy is") 
print(Model_Accuracy)

```



